import { IRoute } from 'umi-types';
import { ROLE_STATUS } from '@/types/enum';

const routes: IRoute[] = [
  {
    path: '/',
    component: '../layouts/index',
    routes: [
      {
        path: '/',
        title: '首页',
        exact: true,
        component: '../pages/index',
        Routes: ['src/layouts/AuthLayout', 'src/layouts/TabBar'],
      },
      {
        path: '/detail',
        title: '详情',
        exact: true,
        component: '../pages/detail',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/submit-task',
        title: '提交任务',
        exact: true,
        component: '../pages/submit-task',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/task-taker',
        title: '稿件',
        exact: true,
        component: '../pages/task-taker',
        roleStatus: ROLE_STATUS.taker,
        Routes: ['src/layouts/AuthLayout', 'src/layouts/TabBar', 'src/layouts/RoleLayout'],
      },
      {
        path: '/task-dispatcher',
        title: '稿件',
        exact: true,
        component: '../pages/task-dispatcher',
        roleStatus: ROLE_STATUS.dispatcher,
        Routes: ['src/layouts/AuthLayout', 'src/layouts/TabBar', 'src/layouts/RoleLayout'],
      },
      {
        path: '/login',
        title: '登录',
        exact: true,
        component: '../pages/login',
        Routes: ['src/layouts/AuthLayout'],
      },
      { path: '/register', title: '注册', exact: true, component: '../pages/register' },
      {
        path: '/user',
        title: '我的',
        exact: true,
        component: '../pages/user',
        Routes: ['src/layouts/AuthLayout', 'src/layouts/TabBar'],
      },
      {
        path: '/add-order',
        title: '发布稿件',
        exact: true,
        roleStatus: ROLE_STATUS.dispatcher,
        component: '../pages/add-order',
        Routes: ['src/layouts/AuthLayout', 'src/layouts/RoleLayout'],
      },
      {
        path: '/my-bill',
        title: '我的账单',
        exact: true,
        component: '../pages/my-bill',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/withdraw',
        title: '提现',
        exact: true,
        component: '../pages/withdraw',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/feedback',
        title: '意见反馈',
        exact: true,
        component: '../pages/feedback',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/setting',
        title: '设置',
        exact: true,
        component: '../pages/setting',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/contact-us',
        title: '联系客服',
        exact: true,
        component: '../pages/contact',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/follow-us',
        title: '关注公众号',
        exact: true,
        component: '../pages/follow',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/reset-password',
        title: '重置登录密码',
        exact: true,
        component: '../pages/reset-password',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/rename',
        title: '修改昵称',
        exact: true,
        component: '../pages/rename',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/avatar',
        title: '修改头像',
        exact: true,
        component: '../pages/avatar',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/banks',
        title: '我的银行卡',
        exact: true,
        component: '../pages/banks',
        Routes: ['src/layouts/AuthLayout'],
      },
      {
        path: '/add-bank',
        title: '添加银行卡',
        exact: true,
        component: '../pages/add-bank',
        Routes: ['src/layouts/AuthLayout'],
      },
      // {
      //   path: '/reset-trade-password',
      //   title: '重置交易密码',
      //   exact: true,
      //   component: '../pages/reset-trade-password',
      //   Routes: ['src/layouts/AuthLayout'],
      // },
      {
        path: '/404',
        title: '404',
        component: '../pages/404',
      },
    ],
  },
];

export default routes;
